### ISSUE TITLE
Quick Question RE: new Book txt files

### ISSUE THREAD

**Issue by rjbprime** [jeheydorn/nortantis#1]
I have a question regarding the addition of new book txt files. Where would one find new premade sets to import? Or is it fairly easy to make new ones? Googling does not seem to bring up anything, but I must admit, I didn't look for long.

Is there a script of some sort to automate this, or is it done by hand?

**Comment by jeheydorn** [comment]
Those txt files are the output of a command line based Java program I wrote which uses Stanford's CoreNLP libraries. The parser finds noun-verb pairs, noun-adjective pairs, and names of people and places. The source code for the book parser is not included with the generator for a few reasons:

- Stanford's CoreNLP library has an open source license which requires anything which has a binary link to it to have the same license. So if the book parser were part of the generator, then the generator and anything software that used it and is distributed would need to have the same license.
- Stanford CoreNLP would add about 250MB to the runable jar file, which is 10 times its current size. And the github repository isn't big enough to keep such large binaries around.
- The book parser consumes multiple GBs of RAM and multiple cores for 20 minutes to 2 hours to parse just one book, depending on the length of the book.

If you want the Java source code, I'd be happy to add it to a new public repository, but you would need to download the source code, compile it, and link it to Stanford CoreNLP. Are you still interested?

**Comment by rjbprime** [comment]
Nah, that's all good. Haven't done code compiling for several years, and I have trouble doing so nowadays. Haven't touched Java for even longer.

All good though, I'll just have to come up with place names instead, and add them after exporting the image.

**Comment by jeheydorn** [comment]
Sounds good.

By the way, as another option, you can use the editor in Nortantis to change place names before exporting the image. Just go to Launch Editor from the Editor menu, then select the text tool.

**Comment by rjbprime** [comment]
Yeah I saw that. Was hoping for an easy solution that I could get random place names from various real world cultures. All good though.

**Comment by Tr35n3r** [comment]
Hi there. First - this Map generatiar is great! Good Job oin this one!
Secondly, I have created some .txt files that I have added to the assets\books folder, but the program does not take these names, locations, etc. into account even when I select the files in the preferences. It still takes names, locations etc. from the original .txt files even when I deselect them. I need to customize a file so that my own .txt. Files are taken into account? The files have the same ending as the original files, for example myownfile_verb_pairs.txt, myownfile_person_names.txt etc. Any Idea why its not working?
