### ISSUE TITLE
broken language

### ISSUE THREAD

**Issue by PalePyth** [jeheydorn/nortantis#13]
I wrote titles in Russian, saved the map, opened it again and now it's broken!
https://i.ibb.co/KVPKbh4/112121212.png
Any help?

**Comment by jeheydorn** [comment]
I've never tried to edit a ma with a character set other than english, so
I'm not surprised it doesn't work. The issue seems to be that the Russian
characters aren't working with UTF-8, but I don't know why. KOI8-R doesn't
work either. I tried switching the character set in Nortantis, but it just
causes the characters to be messed up in some other way. I'll make a note
about this issue, but I'm not sure what it will take to fix it.

**Comment by jeheydorn** [comment]
I figured out that the issue is caused by Nortantis using java property files to store map settings, and apparently the escaping the properties files do is breaking non-latin characters. I'm fixing this by converting Nortantis files into JSON. So far, it works with the word 'текстовый', but I'll need to do some more testing before I push out the change. 

Note that this change will mean that the old '.properties' files we'll need to be converted to the new file format, which I'm planning to call '.nort'. When you open the file, Nortantis will tell you that it will convert it when you save.

**Comment by PalePyth** [comment]
Thank you. You might want to use the pangram "Съешь ещё этих мягких французских булок, да выпей же чаю" - this phrase contains all Russian letters

**Comment by jeheydorn** [comment]
Thanks. That block of text worked in my test.

I've pushed this change to the master branch and updated the executable jar file. Let me know if you hit any trouble with it.
