### ISSUE TITLE
Previously generated map cannot be opened 

### ISSUE THREAD

**Issue by mattpanyor** [jeheydorn/nortantis#17]
I'm trying to import a .properties file in, that was made in an older version of this app.
I have some work in there I do not wish to lose.

Error prompt: Error while creating map: Cannot invoke "java.util.List.stream()" because "cityDrawTasks" is null.

The  map I'm trying to import: https://pastebin.com/8Lq8NmMA

**Comment by jeheydorn** [comment]
[newworldv2.zip](https://github.com/jeheydorn/nortantis/files/14776791/newworldv2.zip)

I don't know how this happened, but somehow your map has edits but doesn't have text edits. The reason this should be impossible is because all generated maps have at least a title, and the editor never actually deletes text; it just sets the text to empty, which causes it to no longer be drawn.

I hacked my code do force your mapped to load, then saved it off as a nort file. So you should be able to open it now. It's attached. 

I'll plan to add a fix to better handle this in the future, but it will be a while before I release it, since I have other ongoing projects in my dev branch.

**Comment by jeheydorn** [comment]
This is now fixed in my dev branch.
