### ISSUE TITLE
UI smears all over

### ISSUE THREAD

**Issue by Aran-Tar** [jeheydorn/nortantis#18]
Every few seconds to a few minutes, the UI smears: extra map images appear and cover the icons and buttons, the main map is blotted out. When I enlarge or reduce window size, the trouble goes away, only to repeat after a few seconds. I use window 11, this happened with both version 2 and 2.6

**Comment by jeheydorn** [comment]
It sounds like your problem is caused by either a problem with your graphics driver on your machine, or a bug in Java that is exposed by interacting with those graphics drivers. Unfortunately, this means I can't fix it. I did, however, figure out that I can disable direct 3D in the Java virtual machine arguments that the installed version of Nortantis uses, and on at least on one of the machines I tested on, that eliminates a much less severe rendering issue (components on the window disappeared when logging out and then logging back in). I pushed this change into version 2.7 and updated the beta version download link with that version. Could you try that version and let me know if it works? 

Note - You'll need to bypass the Windows Defender warning since I haven't yet submitted that version to Microsoft for review to disable the windows defender warning yet. And if you're using Microsoft Edge, you'll also have to tell it to keep the download despite the file being untrusted. If you're not comfortable doing that, you can wait until I've submitted it to Microsoft, which could be a week or more.

If it doesn't work, then my only suggestion is to try updating your graphics driver.

**Comment by Aran-Tar** [comment]
Did not check everything, but seems to be working fine. THX!

**Comment by jeheydorn** [comment]
I'm glad it's working.
