### ISSUE TITLE
png icon issue

### ISSUE THREAD

**Issue by pverkind** [jeheydorn/nortantis#21]
I tried adding a new png image to the decorations/other/ icon folder in my custom images folder. 
However, after refreshing (Refresh Images and Redraw), a small square icon is shown for all the icons in that folder instead of the thumbnail in the decorations window, and when I try to draw the icon (see image below), I get the following error message: "Unrecognized buffered image type: TYPE_BYTE_INDEXED".

![image](https://github.com/jeheydorn/nortantis/assets/16897431/0f88ed99-1366-4506-9eab-b6ccf43d95b0)

I assume there's something wrong with the way the png file was stored; but I tried with some other png files from the internet, and all had the same problem. Do I have to save png files with very specific settings? 

If it's relevant: I'm on a Windows 10 machine.

Thanks for the brilliant program!

**Comment by jeheydorn** [comment]
It looks like the images are a type I didn't account for when writing my
code that handles image abstraction. Try opening the images in Gimp or
Krita, then re-export them to PNG.

I'll plan to do a fix to handle this correctly, but it will be some time,
maybe a few months, before I push out a new version, unless this issue is
hit by enough people to justify a quick fix in my master branch.

If you could attach an image that hits this issue, that would be helpful.

**Comment by pverkind** [comment]
Thanks for solving this!
A workaround that worked for me was to open the PNG in gimp, copy and paste into a new file, and save the new file.

**Comment by jeheydorn** [comment]
Sounds good. The fix is in the beta version for now. It might be a couple
months before it moves to the main installers.
