### ISSUE TITLE
Long loading time

### ISSUE THREAD

**Issue by MatveySuper** [jeheydorn/nortantis#27]
Hello, I have encountered a small problem. I saved my map and decided to finish it the next day. but it has been loading for 3 hours (what should I do?
Maybe it's the file type? I saved the file as "FANTASY.nort)

**Comment by jeheydorn** [comment]
That's a new one on me. What Nortantis version are you using? You can check the version in Help > About Nortantis. Also, are you opening the file by double clicking it in your file explorer, or are you opening Nortantis first and then opening your nort file using the File menu?

Nortantis has a logging window that has information that might help. It's in the lower-left corner of the main window. It's hidden by default, so you'll need to drag it up to open it. Here's a screenshot of it.
![image](https://github.com/user-attachments/assets/ceb19caf-2495-4e50-be4b-a1237873834e)
After attempting to open your map, could you grab the contents of that logging window and included in this issue?

And one more thing that would help - if you're willing to share your nort file publicly, could you attach it to this issue? You'll have to put it in a zip file for GitHub to allow attaching it.

**Comment by MatveySuper** [comment]
I downloaded it only the day before yesterday, I think the version is the
latest. Be sure to check in when I get home. I open the file through the
"File" window in Nortantis

I'll upload the file to Github a little later. Thanks for the quick
response

чт, 22 авг. 2024 г., 21:17 jeheydorn ***@***.***>:

**Comment by jeheydorn** [comment]
Thanks for the information, and thanks for reporting this issue. The issue turned out to be a one-line mistake I made with processing icons that are at least partially off the map. When that happened, they would draw far more slowly than normal.

I pushed out a fix to this in my master branch and updated the beta version installer (version 2.84) on the website. Could you give it a try? I'm assuming you're working with Windows, but if you need an Ubuntu installer, just let me know. If you are using Windows, you'll have to click through the Windows Defender warnings to allow the installer to run because I haven't submitted it to Microsoft for review; I only do that when releasing a major version.
