### ISSUE TITLE
Color Map Error

### ISSUE THREAD

**Issue by SirJackDaReaper** [jeheydorn/nortantis#29]
Upon making a map and doing intensive editing to it with colors the map had a problem loading. And in trying to fix it by copying the map files into one new folder to repair so data wasn't lost. A new error appears when possibly reaching the max number of colors. The file shows it's at 255 colors on the map, and it's to represent countries in a time of war in the map. Below is the error:

Error while creating map: Color Parameter outside of expected range: Red Green Blue

This seems to be a basic java error, but I am unaware of how to fix this myself. This may be a color limit bug with Norton itself or something else from repairing lost work by coping code using Notepad++.

**Comment by SirJackDaReaper** [comment]
[Map.ZIP](https://github.com/user-attachments/files/17049654/Map.ZIP)

**Comment by jeheydorn** [comment]
There is a bug in Nortantis where it can only have 255 colors. The fix
isn't hard - I simply need to use an image type that supports more than 256
values per pixel when drawing color indexes when drawing region colors. The
reason I haven't done this is because it will take (a little) more memory,
and I didn't think anyone would ever actually create a map with that many
colors. But you proved me wrong :)

I went ahead and fixed this in my master branch and updated the beta
version installer with the fix, so you can try the fix now. The new version
is 2.85. You'll have to click through the Windows Defender warnings because
I haven't submitted the installer for Microsoft's review yet. If you're
concerned about that, I can submit it now, but it will take about a week
and a half for them to review it.

**Comment by SirJackDaReaper** [comment]
Thank you I'll let you know how it goes!
