### ISSUE TITLE
Stuck at adding grunge

### ISSUE THREAD

**Issue by amatsune** [jeheydorn/nortantis#6]
It goes up to adding grunge, but not past that. The button to generate becomes usable again, but no map pops out.

**Comment by jeheydorn** [comment]
That's caused by me not properly handling an out of memory error. I fixed
it in my master branch a while ago but forgot to update the zip file. I
updated it just now. Could you try again?

After the fix you will be less likely to hit the out of memory error, but
in theory it can still happen because my algorithm for determining the
maximum resolution to allow you to generate at based on memory available to
java is only approximate. For example, if you use your own background image
or icons, I don't adjust the maximum resolution based on the images you
supply. But if it does happen, you'll get an error popup while generating,
telling you what happened. If you get that error popup, you'll need to
either reduce the resolution you're generating at, or increase the amount
of memory you give to Java.

Thanks for the feedback.

**Comment by amatsune** [comment]
Thanks, Ill try
