### ISSUE TITLE
Add Cave Icons?

### ISSUE THREAD

**Issue by whinis** [jeheydorn/nortantis#9]
Hello, I was wondering if there could possible be the ability to add caves somehow? Would be a nice thing to add to mountains even if added manually.

**Comment by jeheydorn** [comment]
That's an interesting idea. You could try doing that by adding the cave
icon as a city under assets/icons/cities/<group name>/. I recommend you
create edits for the map first so the generator doesn't try to place the
cave city for you. Just opening the editor, then closing it and saving your
map, will bake the changes so that the generator can't change them.

Once you've done that, use the icon editor to put the cave wherever you
want. Note that the width the image is drawn with is encoded into the file
name, although that width will vary if you adjust the resolution slider in
the background tab.

If you would rather have the cave icon show up randomly in mountain ranges,
you could add it to the folder for the icons for that mountain type. But if
you go this route, you won't be able to stop the generator from using it.
Although you can click the polygon in the editor to cause it to randomly
select a new image for that particular mountain, and keep clicking this
until you either get the cave you want or swap out the cave for another
image on that polygon. But if you then go and change the icon files again
for that mountain type, you might have to repeat all of these steps. Also,
mountains give you no control over the size icon draws at. It's determined
by the size of the polygon the mountain is drawn on.

**Comment by whinis** [comment]
Thanks, I will try the first option as I am currently using the editor to place caves where players have been

**Comment by whinis** [comment]
This worked pretty well, took the mountain image and made it a "city" with a cave icon
